name: CI
on:
  push:
    branches: [master, release-*, feature/*]
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
      - '[0-9]+.[0-9]+.[0-9]+-*'
  pull_request:
  workflow_dispatch:

permissions:
  contents: read
  actions: read
  checks: write
  packages: read
env:
  DOTNET_NOLOGO: true
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.2
        with:
          fetch-depth: 0
      - name: Install .NET SDK
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 10.0.x
          source-url: https://nuget.pkg.github.com/gigi81/index.json
        env:
          NUGET_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Build
        run: dotnet build LibGit2Sharp.sln --configuration Release
      - name: Upload packages
        uses: actions/upload-artifact@v4.3.1
        with:
          name: NuGet packages
          path: artifacts/package/
          retention-days: 7
      - name: Verify trimming compatibility
        run: dotnet publish TrimmingTestApp
  test:
    name: Test / ${{ matrix.os }} / ${{ matrix.tfm }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ windows-latest, macos-latest ]
        tfm: [ net8.0, net10.0 ]
        include:
          - os: windows-latest
            tfm: net472
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.2
        with:
          fetch-depth: 0
      - name: Install .NET SDK
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: |
            10.0.x
            8.0.x
          source-url: https://nuget.pkg.github.com/gigi81/index.json
        env:
          NUGET_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Diagnostics
        run: |
          dotnet --info
          uname -m
      - name: Run ${{ matrix.tfm }} tests
        run: dotnet test LibGit2Sharp.sln --configuration Release --framework ${{ matrix.tfm }} --collect:"XPlat Code Coverage" --logger "GitHubActions" --logger "trx;LogFileName=test-results.trx" /p:ExtraDefine=LEAKS_IDENTIFYING /p:CoverletOutputFormat=opencover || true
      - name: Test Report
        uses: dorny/test-reporter@v1.9.1
        if: ${{ always() && (github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name == github.repository) }}
        with:
          name: test-results-${{ matrix.os }}-${{ matrix.tfm }}
          path: "**/*-results.trx"
          reporter: dotnet-trx
          fail-on-error: true
      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: ${{ always() }}
        with:
          name: test-results-${{ github.job }}-${{ matrix.os }}-${{ matrix.tfm }}
          path: |
            **/*.trx
      - name: Upload coverage
        uses: actions/upload-artifact@v4
        with:
          name: Code coverage ${{ matrix.os }} ${{ matrix.tfm }}
          path: "**/coverage.cobertura.xml"
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        if: runner.os == 'Linux'
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
  test-linux:
    name: Test / ${{ matrix.distro }} / ${{ matrix.arch }} / ${{ matrix.tfm }}
    runs-on: ${{ matrix.runnerImage }}
    strategy:
      matrix:
        arch: [ amd64, arm64 ]
        distro: [ alpine.3.23, fedora.43, ubuntu.22.04, ubuntu.24.04 ]
        tfm: [ net10.0 ]
        include:
          - arch: amd64
            runnerImage: ubuntu-latest
          - arch: arm64
            runnerImage: ubuntu-22.04-arm
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.2
        with:
          fetch-depth: 0
      - name: Run ${{ matrix.tfm }} tests
        run: |
            git_command='git config --global --add safe.directory /app'
            auth_command='dotnet nuget update source gigi81 --username gigi81 --password "$NUGET_AUTH_TOKEN" --store-password-in-clear-text'
            test_command='dotnet test LibGit2Sharp.sln --configuration Release --framework ${{ matrix.tfm }} --collect:"XPlat Code Coverage" --logger "GitHubActions" --logger "trx;LogFileName=test-results.trx" /p:ExtraDefine=LEAKS_IDENTIFYING /p:CoverletOutputFormat=opencover || true'
            docker run --rm --platform linux/${{ matrix.arch }} -v "$PWD:/app" -w /app -e NUGET_AUTH_TOKEN="${{ secrets.GITHUB_TOKEN }}" -e OPENSSL_ENABLE_SHA1_SIGNATURES=1 gittools/build-images:${{ matrix.distro }}-sdk-10.0 sh -c "$git_command && $auth_command && $test_command"
      - name: Test Report
        uses: dorny/test-reporter@v1.9.1
        if: ${{ always() && (github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name == github.repository) }}
        with:
          name: test-results-${{ matrix.distro }}-${{ matrix.arch }}
          path: "**/*-results.trx"
          reporter: dotnet-trx
          fail-on-error: true
      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: ${{ always() }}
        with:
          name: test-results-${{ github.job }}-${{ matrix.distro }}-${{ matrix.arch }}-${{ matrix.tfm }}
          path: |
            **/*-results.trx
            **/TestResults/**/*.trx
            **/*.trx
      - name: Upload coverage
        uses: actions/upload-artifact@v4
        if: ${{ always() }}
        with:
          name: test-results-${{ matrix.distro }}-${{ matrix.arch }}
          path: "**/*-results.trx"
      - name: Upload coverage
        uses: actions/upload-artifact@v4
        with:
          name: Code coverage ${{ matrix.distro }} ${{ matrix.arch }}
          path: "**/coverage.cobertura.xml"
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        if: runner.os == 'Linux'
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
